apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    backstage.io/last-applied-configuration: ${{ values.params | dump }}
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
