apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: entity-scaffolder-template
  title: Example Entity Scaffolder
  description: A comprehensive template for testing entity scaffolder with various field types
spec:
  owner: user:guest
  type: service

  parameters:
    # Step 1: Basic Information
    - title: Basic Information
      required:
        - name
        - description
      properties:
        name:
          title: Component Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: A brief description of this component
          ui:widget: textarea
          ui:options:
            rows: 3
        environment:
          title: Environment
          type: string
          description: Target deployment environment
          default: development
          enum:
            - development
            - staging
            - production
        priority:
          title: Priority Level
          type: number
          description: Priority from 1-10
          default: 5
          minimum: 1
          maximum: 10

    # Step 2: Owner & Team Details
    - title: Owner & Team Details
      required:
        - owner
      properties:
        owner:
          title: Owner
          type: string
          description: The team or user that owns this component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [Group, User]
        teamTags:
          title: Team Tags
          type: array
          description: Tags to categorize this component
          ui:field: EntityTagsPicker
        relatedEntities:
          title: Related Entities
          type: array
          description: Other entities related to this component
          ui:field: MultiEntityPicker
          ui:options:
            catalogFilter:
              kind: [Component, API]

    # Step 3: Repository Configuration
    - title: Repository Configuration
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        repoBranch:
          title: Target Branch
          type: string
          description: Branch to create PR against
          ui:field: RepoBranchPicker
          ui:options: {}
        visibility:
          title: Repository Visibility
          type: string
          default: private
          enum:
            - public
            - private
            - internal

    # Step 4: Technical Configuration
    - title: Technical Configuration
      properties:
        language:
          title: Primary Language
          type: string
          default: typescript
          enum:
            - typescript
            - javascript
            - python
            - go
            - java
          enumNames:
            - TypeScript
            - JavaScript
            - Python
            - Go
            - Java
        framework:
          title: Framework
          type: string
          enum:
            - react
            - angular
            - vue
            - express
            - fastapi
            - spring
        enableDocker:
          title: Enable Docker
          type: boolean
          default: true
          description: Include Dockerfile and docker-compose
        enableCI:
          title: Enable CI/CD
          type: boolean
          default: true
          description: Include GitHub Actions workflows
        ports:
          title: Service Ports
          type: array
          items:
            type: number
          default: [3000]
          description: List of ports exposed by this service

    # Step 5: Advanced Options
    - title: Advanced Options
      properties:
        metadata:
          title: Additional Metadata
          type: object
          description: Custom key-value metadata
          properties:
            costCenter:
              title: Cost Center
              type: string
            region:
              title: Region
              type: string
              enum:
                - us-east-1
                - us-west-2
                - eu-west-1
                - ap-southeast-1
            tier:
              title: Service Tier
              type: string
              enum:
                - tier1
                - tier2
                - tier3
        dependencies:
          title: Dependencies
          type: array
          description: List of dependency configurations
          items:
            type: object
            properties:
              name:
                title: Dependency Name
                type: string
              version:
                title: Version
                type: string
              optional:
                title: Optional
                type: boolean
                default: false
        secretsEnabled:
          title: Enable Secrets Management
          type: boolean
          default: false
        debugMode:
          title: Debug Mode
          type: boolean
          default: false
          description: Enable verbose logging

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          params: ${{ parameters }}

    - id: publish
      name: Publish
      if: ${{ parameters.firstRun != false }}
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: 'main'

    - id: pull-request
      name: Create Pull Request
      if: ${{ parameters.firstRun == false }}
      action: publish:github:pull-request
      input:
        title: "Update ${{ parameters.name }} configuration"
        description: |
          Updates to ${{ parameters.name }}
          
          Environment: ${{ parameters.environment }}
          Owner: ${{ parameters.owner }}
        repoUrl: ${{ parameters.repoUrl }}
        branchName: 'update-${{ parameters.name }}'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Pull Request
        url: ${{ steps['pull-request'].output.remoteUrl }}
